In [14]:
from dataloaders.cifar10 import cifar10_for_classes_TaskIL
from dataloaders.mnist import MNIST_for_classes_TaskIL
import torchvision
import torch
import numpy as np


In [36]:
class_1, class_2 = 0, 1
dataset = torchvision.datasets.CIFAR10('files/', train=True, download=True,
                                transform=torchvision.transforms.Compose([
                                torchvision.transforms.ToTensor(),
                                torchvision.transforms.Normalize(
                                (0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
                            ]),)

dataset.data = torch.cat(
    (np.array(dataset.data[np.array(dataset.targets) == class_1]), np.array(dataset.data[np.array(dataset.targets) == class_2]))
)
dataset.targets = torch.cat(
    (torch.tensor(dataset.targets)[np.array(np.array(dataset.targets)) == class_1], torch.tensor(dataset.targets)[np.array(dataset.targets) == class_2])
)

Files already downloaded and verified


TypeError: expected Tensor as element 0 in argument 0, but got numpy.ndarray

In [15]:
taskM = MNIST_for_classes_TaskIL(0,1)

/home/jsobolewski/.local/lib/python3.8/site-packages/torchvision/datasets/mnist.py:65: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")


In [4]:
classes = np.arange(10)
np.random.shuffle(classes)
classes = list(classes)

task1 = cifar10_for_classes_TaskIL(classes.pop(), classes.pop())
task2 = cifar10_for_classes_TaskIL(classes.pop(), classes.pop())
task3 = cifar10_for_classes_TaskIL(classes.pop(), classes.pop())
task4 = cifar10_for_classes_TaskIL(classes.pop(), classes.pop())
task5 = cifar10_for_classes_TaskIL(classes.pop(), classes.pop())

tasks = [task1 ,task2, task3, task4, task5]

Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified


In [18]:
taskM.dataset

Dataset MNIST
    Number of datapoints: 10842
    Root location: files/
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.1307,), std=(0.3081,))
           )

In [19]:
task1.dataset

Dataset CIFAR10
    Number of datapoints: 10000
    Root location: files/
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
           )

In [30]:
tasks[1].dataset.targets[0]

tensor(0)

In [28]:
taskM.dataset.targets[0]

tensor(0)

In [22]:
for data, target in task1:
    pass

AttributeError: 'Tensor' object has no attribute '__array_interface__'

In [7]:
for batch_idx, (data, target) in enumerate(tasks[0]):
    pass

AttributeError: 'Tensor' object has no attribute '__array_interface__'

In [2]:
ds = cifar10_for_classes_TaskIL(1,2)

Files already downloaded and verified


In [6]:
ds.dataset.targets

10000

In [3]:
x = ds.dataset.targets

unique, counts = np.unique(x, return_counts=True)
unique, counts

(array([0, 1]), array([5000, 5000]))

In [32]:
MNIST_train = torchvision.datasets.MNIST('files/', train=True, download=True,
                                    transform=torchvision.transforms.Compose([
                                    torchvision.transforms.ToTensor(),
                                    torchvision.transforms.Normalize(
                                    (0.1307,), (0.3081,))
                                ]),)

In [34]:
for class_1 in range(10):
    print(len(MNIST_train.data[MNIST_train.train_labels == class_1]))

5923
6742
5958
6131
5842
5421
5918
6265
5851
5949


In [38]:
MNIST_train.data[MNIST_train.train_labels == class_1][:5421].shape

c:\Users\QbaSo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\mnist.py:65: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")


torch.Size([5421, 28, 28])

In [40]:
torch.cat((MNIST_train.data[MNIST_train.train_labels == class_1][:5421], MNIST_train.data[MNIST_train.train_labels == class_1][:5421]))

c:\Users\QbaSo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\mnist.py:65: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")


torch.Size([10842, 28, 28])

In [42]:
torch.cat((MNIST_train.targets[MNIST_train.train_labels == class_1][:5421], MNIST_train.targets[MNIST_train.train_labels == class_1][:5421])).shape

c:\Users\QbaSo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\mnist.py:65: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")


torch.Size([10842])

In [4]:
classes = np.arange(10)
np.random.shuffle(classes)
classes = list(classes)

task1 = MNIST_for_classes_TaskIL(classes.pop(), classes.pop())
task2 = MNIST_for_classes_TaskIL(classes.pop(), classes.pop())
task3 = MNIST_for_classes_TaskIL(classes.pop(), classes.pop())
task4 = MNIST_for_classes_TaskIL(classes.pop(), classes.pop())
task5 = MNIST_for_classes_TaskIL(classes.pop(), classes.pop())

tasks = [task1 ,task2, task3, task4, task5]

c:\Users\QbaSo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\mnist.py:65: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")


In [10]:
task4.dataset

Dataset MNIST
    Number of datapoints: 11263
    Root location: files/
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.1307,), std=(0.3081,))
           )

In [43]:
d = {}
[d.update({f"acc_task_{i}": i}) for i in range(3)]
d

{'acc_task_0': 0, 'acc_task_1': 1, 'acc_task_2': 2}

In [46]:
d = {}
i = 0
d.update({f"acc_task_{i}": i})
d

{'acc_task_0': 0}

In [18]:
for batch_idx, (data, target) in enumerate(task2):
    print(batch_idx)
    if batch_idx % 1000 == 0:
        print("yes")

0
yes
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87


In [118]:
for param in model.fc2.parameters():
    param.requires_grad = True

In [119]:
param.grad

In [127]:
model['0']

TypeError: 'NetTaskIL' object is not subscriptable

In [57]:
model.fc2['0']

Linear(in_features=50, out_features=2, bias=True)

In [61]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.1
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [72]:
optimizer.param_groups

[{'params': [Parameter containing:
   tensor([[[[ 1.7750e-01, -7.1402e-02, -1.0231e-01, -6.9570e-02, -7.6973e-02],
             [-5.8293e-02, -2.1032e-01, -1.9163e-01, -1.4854e-01, -2.0554e-01],
             [ 1.4700e-01, -5.2378e-02,  1.3265e-01, -1.9940e-01, -1.3649e-01],
             [-6.2988e-03,  9.8077e-03, -5.0981e-02,  1.9542e-01, -1.8439e-01],
             [ 2.5899e-01,  1.2793e-01, -7.3893e-02,  1.8779e-01, -9.1176e-02]]],
   
   
           [[[-1.3864e-01, -1.3950e-01,  8.8245e-02,  1.5420e-01, -1.5735e-01],
             [-1.5873e-01, -1.8940e-01, -1.0020e-01, -8.9142e-02, -1.7878e-01],
             [-5.2699e-03, -9.5091e-02,  1.4554e-01, -1.5369e-01,  9.8657e-02],
             [ 1.7777e-03,  1.9881e-01, -4.0438e-02,  8.1564e-02, -3.0672e-02],
             [ 6.0375e-02,  2.5780e-01,  1.5573e-01,  2.5061e-01,  8.2206e-02]]],
   
   
           [[[ 7.1000e-02, -1.2714e-01, -1.0338e-01, -1.1051e-01, -2.2047e-01],
             [-2.5585e-02, -1.3976e-01,  2.3560e-02, -2.5741e-01,

In [90]:
model

NetTaskIL(
  (conv1): Conv2d(1, 10, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(10, 20, kernel_size=(5, 5), stride=(1, 1))
  (conv2_drop): Dropout2d(p=0.5, inplace=False)
  (fc1): Linear(in_features=320, out_features=50, bias=True)
  (fc2): ModuleDict(
    (0): Linear(in_features=50, out_features=2, bias=True)
    (1): Linear(in_features=50, out_features=2, bias=True)
    (2): Linear(in_features=50, out_features=2, bias=True)
    (3): Linear(in_features=50, out_features=2, bias=True)
    (4): Linear(in_features=50, out_features=2, bias=True)
  )
)

In [95]:
optimizer = optim.SGD([
                {'params': model.conv1.parameters()},
                {'params': model.conv2.parameters()},
                {'params': model.conv2_drop.parameters()},
                {'params': model.fc1.parameters()},
                {'params': model.fc2.parameters(), 'lr': 1e-3}
            ], lr=1e-3)

In [96]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.001
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0

Parameter Group 1
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.001
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0

Parameter Group 2
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.001
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0

Parameter Group 3
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.001
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0

Parameter Group 4
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.001
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [114]:
optimizer.param_groups[4]['lr'] = 0.1

In [115]:
optimizer.param_groups[4]['lr']

0.1

In [104]:
for g in optimizer.param_groups:
    print(g)

{'params': [Parameter containing:
tensor([[[[ 1.7750e-01, -7.1402e-02, -1.0231e-01, -6.9570e-02, -7.6973e-02],
          [-5.8293e-02, -2.1032e-01, -1.9163e-01, -1.4854e-01, -2.0554e-01],
          [ 1.4700e-01, -5.2378e-02,  1.3265e-01, -1.9940e-01, -1.3649e-01],
          [-6.2988e-03,  9.8077e-03, -5.0981e-02,  1.9542e-01, -1.8439e-01],
          [ 2.5899e-01,  1.2793e-01, -7.3893e-02,  1.8779e-01, -9.1176e-02]]],


        [[[-1.3864e-01, -1.3950e-01,  8.8245e-02,  1.5420e-01, -1.5735e-01],
          [-1.5873e-01, -1.8940e-01, -1.0020e-01, -8.9142e-02, -1.7878e-01],
          [-5.2699e-03, -9.5091e-02,  1.4554e-01, -1.5369e-01,  9.8657e-02],
          [ 1.7777e-03,  1.9881e-01, -4.0438e-02,  8.1564e-02, -3.0672e-02],
          [ 6.0375e-02,  2.5780e-01,  1.5573e-01,  2.5061e-01,  8.2206e-02]]],


        [[[ 7.1000e-02, -1.2714e-01, -1.0338e-01, -1.1051e-01, -2.2047e-01],
          [-2.5585e-02, -1.3976e-01,  2.3560e-02, -2.5741e-01,  3.0619e-02],
          [ 1.5004e-01,  8.5427e-0

In [77]:
for name,param in model.named_parameters():
    print(name, param)

conv1.weight Parameter containing:
tensor([[[[ 1.7750e-01, -7.1402e-02, -1.0231e-01, -6.9570e-02, -7.6973e-02],
          [-5.8293e-02, -2.1032e-01, -1.9163e-01, -1.4854e-01, -2.0554e-01],
          [ 1.4700e-01, -5.2378e-02,  1.3265e-01, -1.9940e-01, -1.3649e-01],
          [-6.2988e-03,  9.8077e-03, -5.0981e-02,  1.9542e-01, -1.8439e-01],
          [ 2.5899e-01,  1.2793e-01, -7.3893e-02,  1.8779e-01, -9.1176e-02]]],


        [[[-1.3864e-01, -1.3950e-01,  8.8245e-02,  1.5420e-01, -1.5735e-01],
          [-1.5873e-01, -1.8940e-01, -1.0020e-01, -8.9142e-02, -1.7878e-01],
          [-5.2699e-03, -9.5091e-02,  1.4554e-01, -1.5369e-01,  9.8657e-02],
          [ 1.7777e-03,  1.9881e-01, -4.0438e-02,  8.1564e-02, -3.0672e-02],
          [ 6.0375e-02,  2.5780e-01,  1.5573e-01,  2.5061e-01,  8.2206e-02]]],


        [[[ 7.1000e-02, -1.2714e-01, -1.0338e-01, -1.1051e-01, -2.2047e-01],
          [-2.5585e-02, -1.3976e-01,  2.3560e-02, -2.5741e-01,  3.0619e-02],
          [ 1.5004e-01,  8.5427e-

In [58]:
for param in model.fc2.parameters():
    print(param)

Parameter containing:
tensor([[ 0.0169, -0.0496, -0.0709, -0.0274,  0.0490, -0.0006,  0.1369, -0.3032,
         -0.0069, -0.0466, -0.0214,  0.0931, -0.1453,  0.0865, -0.2232,  0.1019,
          0.1565,  0.0727, -0.0611,  0.0457,  0.1310, -0.1183,  0.0995, -0.1060,
         -0.0129,  0.0129,  0.0857, -0.0154,  0.0989,  0.0509, -0.0878, -0.1352,
          0.0485,  0.2958,  0.3424, -0.1721, -0.0200,  0.0599,  0.0044,  0.0286,
          0.1109,  0.0710,  0.1084, -0.1844, -0.0337,  0.0558,  0.1489,  0.0147,
          0.1231,  0.0428],
        [ 0.1338,  0.0076,  0.0351, -0.1235, -0.0640,  0.1287, -0.0542,  0.2228,
          0.0379,  0.0392,  0.0654, -0.0882,  0.2145, -0.0629,  0.1991, -0.1291,
          0.0215,  0.0126,  0.0051, -0.1810, -0.0627,  0.0254, -0.0888,  0.0783,
         -0.0693, -0.1533, -0.1298,  0.0319, -0.1487, -0.0289, -0.0941,  0.0544,
         -0.0165, -0.3085, -0.2892, -0.0747,  0.1405, -0.0387,  0.1143, -0.1140,
          0.0496, -0.0742,  0.0246,  0.2362,  0.2374,  0.09

In [20]:
import torch
from Nets import NetTaskIL
from taskIL import train_validation_all_classes
from dataloaders.mnist import MNIST_for_classes_TaskIL
from dataloaders.noise import dataloader_pretraining_gray
import numpy as np
import torch.optim as optim
import torch.nn.functional as F

def train_validation_all_classes(model, optimizer, tasks, device, rehersal_loader, epoch=1, log_interval = 1000):
    train_losses = []
    tasks_acc = [[], [], [], [], []]
    exemplers = []

    rehersal_iterator = iter(rehersal_loader)

    model.train()
    for taskNo in range(len(tasks)):
        for batch_idx, (data, target) in enumerate(tasks[taskNo]):

            # training on task
            output = model(taskNo, data.to(device))
            loss = F.cross_entropy(output, target.to(device))

            # noise rehersal
            rehersal_data = next(rehersal_iterator)
            output = model(taskNo, rehersal_data[0].to(device))
            loss += F.cross_entropy(output, rehersal_data[1].to(device))

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            if batch_idx % log_interval == 0:
                print(batch_idx % log_interval == 0, batch_idx, log_interval)
                print(f"Train [{batch_idx * len(data)} / {len(tasks[taskNo].dataset)}]       loss: {loss.item()}")
                for i in range(len(tasks)):
                    curr_task_acc = test(model, tasks[i], i, device, print_accuracy=False)
                    tasks_acc[i].append(curr_task_acc)
                    print({f"acc_task_{i}": curr_task_acc})

            train_losses.append(loss.cpu().item())
            exemplars = tasks[taskNo].batch_size * batch_idx
            exemplers.append(exemplars)
    return train_losses, tasks_acc, exemplers

def test(model, test_loader, taskNo, device, print_accuracy=True):
    model.eval()
    test_loss = 0
    correct = 0
    with torch.no_grad():
        for data, target in test_loader:
            output = model(taskNo, data.to(device))
            test_loss += F.cross_entropy(output, target.to(device), size_average=False).item()
            pred = output.data.max(1, keepdim=True)[1].cpu()
            correct += pred.eq(target.data.view_as(pred)).sum()
    test_loss /= len(test_loader.dataset)
    if print_accuracy:
        print('\nTest set: Avg. loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
            test_loss, correct, len(test_loader.dataset),
            100. * correct / len(test_loader.dataset)))
    return 100. * correct / len(test_loader.dataset)



if torch.cuda.is_available():
    device = 'cuda'
else:
    device = 'cpu'

classes = np.arange(10)
np.random.shuffle(classes)
classes = list(classes)

task1 = MNIST_for_classes_TaskIL(classes.pop(), classes.pop())
task2 = MNIST_for_classes_TaskIL(classes.pop(), classes.pop())
task3 = MNIST_for_classes_TaskIL(classes.pop(), classes.pop())
task4 = MNIST_for_classes_TaskIL(classes.pop(), classes.pop())
task5 = MNIST_for_classes_TaskIL(classes.pop(), classes.pop())

tasks = [task1 ,task2, task3, task4, task5]

rehersal_loader = dataloader_pretraining_gray("dead_leaves-squares", no_classes=2)


model = NetTaskIL(10).to(device)
optimizer = optim.SGD(model.parameters(), lr=0.1)

train_losses, tasks_losses, exemplers = train_validation_all_classes(model, optimizer, tasks, device, rehersal_loader, epoch=1, log_interval = 10)

c:\Users\QbaSo\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datasets\mnist.py:65: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")


Loading data from data/dead_leaves-squares/ as imagefolder
True 0 10
Train [0 / 11263]       loss: 1.405999779701233


c:\Users\QbaSo\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


{'acc_task_0': tensor(49.9157)}
{'acc_task_1': tensor(38.4977)}
{'acc_task_2': tensor(53.2895)}
{'acc_task_3': tensor(50.2619)}
{'acc_task_4': tensor(47.1899)}
True 10 10
Train [1280 / 11263]       loss: 1.2727913856506348
{'acc_task_0': tensor(95.7294)}
{'acc_task_1': tensor(53.7335)}
{'acc_task_2': tensor(53.6713)}
{'acc_task_3': tensor(50.5372)}
{'acc_task_4': tensor(47.6161)}
True 20 10
Train [2560 / 11263]       loss: 1.3991427421569824
{'acc_task_0': tensor(96.9102)}
{'acc_task_1': tensor(43.6385)}
{'acc_task_2': tensor(20.2699)}
{'acc_task_3': tensor(50.6082)}
{'acc_task_4': tensor(48.1222)}
True 30 10
Train [3840 / 11263]       loss: 0.7461702823638916
{'acc_task_0': tensor(97.5140)}
{'acc_task_1': tensor(47.5628)}
{'acc_task_2': tensor(26.3251)}
{'acc_task_3': tensor(60.0817)}
{'acc_task_4': tensor(49.1521)}
True 40 10
Train [5120 / 11263]       loss: 0.7391754984855652
{'acc_task_0': tensor(98.3575)}
{'acc_task_1': tensor(49.3918)}
{'acc_task_2': tensor(24.2120)}
{'acc_task_3

KeyboardInterrupt: 

In [29]:
torch.cat((task1.dataset.data,task1.dataset.data)).shape

torch.Size([22526, 28, 28])